### PR TITLE
ROS2 Control!

### PR DESCRIPTION
**Pull request by DLu**
This plus https://github.com/ros-planning/moveit2/pull/1315 and https://github.com/ros-planning/moveit2/pull/1316 should make the demo work.

### CODE REVIEW

**Comment by mikeferguson** [comment]
SWEEET! I'll try it out in the morning

**Comment by DLu** [comment]
Any luck?

**Comment by mikeferguson** [comment]
So, I didn't exactly try this out - but I've got things working with your MSA branch - posting notes there to help get it merged

**Comment by mikeferguson** [comment]
For posterity - this was the diff when I re-exported from the MSA: https://github.com/mikeferguson/ubr_reloaded/pull/7/commits/709abc0fdda16b2e9b584e6873f0f1f31c036198

**Pull request merged**
